
services:
  app:
    image: php:8.1-fpm
    container_name: laravel-app
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network


  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app-network

  frontend:
    image: node:16
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
